services:
  - type: web
    name: genai-chatbot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
    buildFilter:
      paths:
        - backend/**

  - type: web
    name: genai-chatbot-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - frontend/**
